Resources:
  BookmarksTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: bookmarkId
          AttributeType: S
      KeySchema:
        - AttributeName: bookmarkId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.tableNames.bookmarks}
